### ISSUE TITLE
2.6.6 Action { request => ??? } broken but Action { ??? } working

### ISSUE THREAD

**Issue by MarkRBM** [leanovate/play-mockws#40]
I have 

```
MockWS {
  case (GET, "blah") => Action {Ok("valid json")}
}
```
This works great, I get a 200 containing "valid json"

If I modify it to
```
MockWS {
  case (GET, "blah") => Action {request => Ok("valid json")}
}
```
I now get 

```
Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: [B@4865434e; line: 1, column: 2]
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: [B@4865434e; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:456)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2689)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3847)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3765)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2050)
	at play.api.libs.json.jackson.JacksonJson$.parseJsValue(JacksonJson.scala:232)
	at play.api.libs.json.StaticBinding$.parseJsValue(StaticBinding.scala:12)
	at play.api.libs.json.Json$.parse(Json.scala:175)
	at play.api.libs.ws.JsonBodyReadables.$anonfun$readableAsJson$1(JsonBodyReadables.scala:24)
	at play.api.libs.ws.StandaloneWSResponse.body(StandaloneWSResponse.scala:92)
	at play.api.libs.ws.StandaloneWSResponse.body$(StandaloneWSResponse.scala:90)
	at play.api.libs.ws.ahc.AhcWSResponse.play$api$libs$ws$WSResponse$$super$body(AhcWSResponse.scala:19)
	at play.api.libs.ws.WSResponse.body(WSResponse.scala:83)
	at play.api.libs.ws.WSResponse.body$(WSResponse.scala:83)
	at play.api.libs.ws.ahc.AhcWSResponse.body(AhcWSResponse.scala:19)
```

Any ideas of where I should start looking to figure this out? I really need access to the request

edit:

If I add a println into the block Action is taking in the first example it gets hit, if I enter it into the second example it never gets hit

**Comment by Ir1sh** [comment]
Whilst debugging I noticed the following difference

in the first example when I hit line 117 in FakeWSRequestHolder.scala action = Action(BodyParser(ignore)) 

but in the second it is Action(BodyParser(anyContent)) 

still trying to dig in further

**Comment by Ir1sh** [comment]
it works if I build my action with `DefaultActionBuilder(BodyParser.ignore(AnyContentAsEmpty))(global)`  instead of calling `MockWSHelpers.Action`

**Comment by yanns** [comment]
Is it a problem only with `MockWS` or also with a normal play action?

**Comment by yanns** [comment]
I tried to reproduce your issue, but failed: https://github.com/leanovate/play-mockws/pull/45

Please open the issue again if you have more details.

**Comment by vojtechsoban** [comment]
Our issue was that we add Content-Type to every method including GET, it is not prohibited and it works.  Some APIs have empty body for instance  [CouchDB](http://docs.couchdb.org/en/stable/api/database/compact.html) and it is not testable with MockWS. It should handle empty body properly.

**Comment by yanns** [comment]
@vojtechsoban Thx for your failing test! That's the best way for me to fix.
Or do you already have an idea how to fix that, and would you like to propose a PR?

**Comment by vojtechsoban** [comment]
I'm sorry but I'm new to Scala and currently I have no idea how to fix that.

**Comment by yanns** [comment]
@vojtechsoban If you look at the source code, `Action { block }`  is defined like this:
```
  final def apply(block: => Result): Action[AnyContent] =
    apply(BodyParsers.utils.ignore(AnyContentAsEmpty: AnyContent))(_ => block)
```

If you want to use `Action { request => block }` then you have to set the body parser:
```
  test("mock WS simulates a POST with an empty body") {
    val ws = MockWS {
      case (POST, "/books/_compact") => Action(BodyParser.ignore(AnyContentAsEmpty: AnyContent)) { request =>
        Ok(request.method)
      }
    }
    val response = await(ws.url("/books/_compact").withHttpHeaders(CONTENT_TYPE -> "application/json").post(EmptyBody))
    response.status shouldEqual OK
    ws.close()
  }
```
In that case, it's working.

More inf on https://www.playframework.com/documentation/2.6.x/ScalaBodyParsers
